// <auto-generated />
using Antss.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Antss.Data.Migrations
{
    [DbContext(typeof(AntssContext))]
    [Migration("20220122031828_SeedInitialData")]
    partial class SeedInitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Antss.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNumber = "foo",
                            EmailAddress = "foo",
                            FirstName = "Adam",
                            LastName = "Smith",
                            Location = "foo",
                            UserType = 3
                        },
                        new
                        {
                            Id = 2,
                            ContactNumber = "foo",
                            EmailAddress = "foo",
                            FirstName = "John",
                            LastName = "Jones",
                            Location = "foo",
                            UserType = 2
                        },
                        new
                        {
                            Id = 3,
                            ContactNumber = "foo",
                            EmailAddress = "foo",
                            FirstName = "Peter",
                            LastName = "Taylor",
                            Location = "foo",
                            UserType = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
